### PR TITLE
REPO-3985: Fluentd logging implementation and Documentation enhancements (#19)

### PR DESCRIPTION
**Pull request by mmuller88**
* Adding Fluentd-Cloudwatch helm support

* fixed HelmInstallFluentdRunScript ref

* fixed stackname size limit

* Reduced stackname size

* Documentation about Route53 and DNS zone

### CODE REVIEW

**Comment by mmuller88** [comment]
Big thanks to Tony.
I will check bamboo if everything works as expected with this nice PR.

**Comment by derekhulley** [comment]
https://issues.alfresco.com/jira/browse/REPO-3985
There are a few fixes that we need to take in.
In future, @toniblyx, if you create a branch in the main repo, it will go through automated builds.
Please update RPEO-3985 to capture the details of what has been provided.

**Comment by toniblyx** [comment]
Thanks @derekhulley, I tried that but I didn't have permissions to do so. I'll update RPEO-3985 also with proper info.

**Comment by derekhulley** [comment]
I've added you, @toniblyx, for next time.

**Comment by gavincornwell** [comment]
I'm going ahead with the merge despite a red build as all the failing tests are quarantined on master.

**Pull request merged**
